import type { Metadata } from "next";
// Mengimpor tipe Metadata dari Next.js
// Digunakan untuk mendefinisikan title, description, dll pada halaman

import { Geist, Geist_Mono } from "next/font/google";
// Mengimpor font Geist Sans dan Geist Mono dari Google Fonts via Next.js font optimization

import "./globals.css";
// Mengimpor file CSS global yang berlaku untuk seluruh aplikasi

// Konfigurasi font Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  // Menyimpan font ke CSS variable agar bisa dipakai di seluruh app

  subsets: ["latin"],
  // Menentukan subset karakter yang digunakan (latin agar lebih ringan)
});

// Konfigurasi font Geist Mono (font monospace)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  // CSS variable untuk font monospace

  subsets: ["latin"],
  // Subset karakter latin
});

// Metadata default untuk aplikasi
export const metadata: Metadata = {
  title: "Create Next App",
  // Judul halaman yang tampil di tab browser

  description: "Generated by create next app",
  // Deskripsi halaman (berguna untuk SEO)
};

// Root layout → layout utama yang membungkus semua halaman di App Router Next.js
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // children = isi halaman yang dirender di dalam layout ini
}>) {
  return (
    <html lang="en">
      {/* Tag HTML utama dengan atribut bahasa Inggris */}

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Menggunakan CSS variable dari font Geist Sans & Mono
        // antialiased → membuat teks lebih halus
      >
        {children}
        {/* Semua halaman Next.js akan dirender di sini */}
      </body>
    </html>
  );
}
